[package]
name = "dolang-shell-vfs"
version = "0.1.1"
description = "Shell VFS daemon for Do language integrations."
edition = "2024"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
autobins = false

[[bin]]
name = "dolang-vfs"
path = "src/main.rs"
test = false

[features]
default = ["winreg", "winscm"]
winreg = ["dep:dolang-vfs-winreg"]
winscm = ["dep:dolang-vfs-winscm"]

[dependencies]
dolang-vfs = { path = "../dolang-vfs", version = "0.1.1" }
dolang-vfs-winreg = { path = "../dolang-vfs-winreg", version = "0.1.1", optional = true }
dolang-vfs-winscm = { path = "../dolang-vfs-winscm", version = "0.1.1", optional = true }

[dev-dependencies]
base64 = "0.22.1"
typed-path.workspace = true
tempfile = "3"
tokio = { version = "1.48.0", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }

[target.'cfg(unix)'.dev-dependencies]
futures = "0.3"
libc = "0.2"
